server:
  port: 8081

logging:
  level:
    app.services.KafkaConsumerService: DEBUG
    app.controller.EmailController : DEBUG
    root: ERROR
  file:
    name: ./notification-service/logs/notification-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n"

spring:
  kafka:
    bootstrap-servers: localhost:9092
  consumer:
    group-id: application-group
    auto-offset-reset: earliest
    producer:
    acks: 1
    retries: 3